### ISSUE TITLE
/usr/local/bin/s3 still references s3fs and not goofys

### ISSUE THREAD

**Issue by mike-zipit** [cloudposse/geodesic#141]
When I run this (in geodesic or the Dockerfile)
```
s3 fstab TF_BUCKET /dev /secrets/tf/
```

The fstab contains:
```
s3fs#TF_BUCKET:/dev /secrets/tf/ fuse _netdev,allow_other,rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions 0 0

```

**Comment by osterman** [comment]
So, in `fstab` the field before the `#` is the the "mount" command used by `fstab`. It calls this script: https://github.com/cloudposse/geodesic/blob/master/rootfs/usr/local/bin/s3fs

**Comment by osterman** [comment]
I realize there is another project [`s3fs-fuse`](https://github.com/s3fs-fuse/s3fs-fuse), but IMO, `s3fs` is just to "valuable" a name to describe what it does, which is why I hijacked it for this purpose. An inheritor of geodesic, for example, could swap out `s3fs` script to implement their own mount logic.

**Comment by osterman** [comment]
Do you have a suggestion for how we could improve it?

**Comment by osterman** [comment]
Documentation has been updated to make this more clear. https://docs.cloudposse.com/geodesic/s3fs/
