### ISSUE TITLE
Allow any of the cold-start resources to be provided as overrides 

### ISSUE THREAD

**Issue by jdn-za** [cloudposse/geodesic#318]
## what
I have several resources that a cold-start would create, such as parent domain or possibly pre-existing root account. I would like to be able to set these as overrides so that the are taken into account (possibly state imported?)

## why
Using existing resources rather than creating new duplicated ones.

**Comment by osterman** [comment]
So in your particular case, you don't want to create the DNS zone, since you already had one and need to piggy back off it.

**Comment by jdn-za** [comment]
In that case yes

**Comment by Nuru** [comment]
Since this issue was opened, we have completely changed the cold start procedure and how it is configured, so this can be viewed as either no longer relevant, something we are never going to get to, or something we have fixed in a different way. In any case, we are not going to do any (more) work on this issue, so we are closing it.
