### ISSUE TITLE
Fix Upload of motd

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#362]
## what
* changes to `public/motd` are not getting published

## why
* we want to do a better job of updating this with important announcements

**Comment by Nuru** [comment]
@osterman I am closing this as fixed, since we now have Geodesic pulling `motd` from `MOTD_URL` https://github.com/cloudposse/geodesic/blob/0fdf51fb8be942af0d17cc3de9592a6530039558/rootfs/etc/profile.d/motd.sh#L6-L8

and we set `MOTD_URL` by default https://github.com/cloudposse/geodesic/blob/0fdf51fb8be942af0d17cc3de9592a6530039558/os/debian/Dockerfile.debian#L91

If you want something more, you can re-open this issue with additional details.
