### ISSUE TITLE
unknown terminal "xterm-termite"

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#365]
## what

On Arch linux someone reported in [slack](https://slack.cloudposse.com) that they get this error:

```sh
✗   (none) ~ ⨠  echo $TERM
xterm-termite
tput: unknown terminal "xterm-termite"
tput: unknown terminal "xterm-termite"
-> Run 'assume-role' to login to AWS
tput: unknown terminal "xterm-termite"
tput: unknown terminal "xterm-termite"
(~4 more times)
```

## why
* Appears that geodesic doesn't have a `terminfo` file for Termite

## remediation

for anyone else with this problem, run it in tmux or simply `export TERM=screen-256color`

**Comment by Nuru** [comment]
Alpine linux (on which Geodesic is based) has support for `termite` but not `xterm-termite`. 
Affected users can add support easily by adding this line to their Dockerfile:
```
RUN curl -sSL https://raw.githubusercontent.com/thestinger/termite/master/termite.terminfo | tic -x -
```
Affected users using shells they cannot customize can work around the issue by executing
```
export TERM=xterm-256color
```
inside the shell on the command line or including that in their Geodesic preferences file.

Closing as `wontfix` because this is the kind of thing that is best left up to Alpine maintainers to handle and there is not enough need for it to warrant special handling.
