### ISSUE TITLE
Add Description section and 'Supported Tags and respective Dockerfile links' subsection to Geodesic docker hub repo

### ISSUE THREAD

**Issue by jonassteinberg1** [cloudposse/geodesic#690]
## Describe the Feature

The geodesic docker repo lacks tag and dockerfile links.  I had to scrutinize the Geodesic Github README and also just kind of search around in the docker repo to get an idea of where Geodesic is at in terms of stability, given that the latest releases are pull request releases, etc.  I'm not quite sure what the intention is, but I think it's fairly typical of robust docker repo's to have a subsection in their description tab that lists all tags with links to the respective Dockerfile.  In my experience one major plus of this is that someone that wants to use a various different/newer/experimental image versions can just go right to this page and figure our what's what.  As it stands this is somewhat difficult to do with Geodesic because there isn't such a page.  So in my case, wanting to begin playing around with baking our Geo images as debian instead of alpine (and therein help y'all stabilize debian in the interest of having Geo on a bit more of a robust distro), I had to search around _all_ the image versions to figure out that I wanted to use 0.142.1-debian.

## Use Case

- Help stabilize debian
- Make switching between Geo versions easy
- Conform to basic Docker hub standards

## Describe Ideal Solution

- Have a description page just like [this](https://hub.docker.com/_/debian)

If I'm missing something and this request is superfluous I'd appreciate the insight.

**Comment by Nuru** [comment]
@jonassteinberg1 

I am sorry you had trouble finding out what Docker tag to use. The documentation on the Docker Hub is something we have been neglecting. We really expect people to come to GitHub and read the README, and to use the current release version as shown on the repo front page. 

I am not sure what you mean by "the latest releases are pull request releases, etc." The releases are listed on the [Releases page](https://github.com/cloudposse/geodesic/releases) with Release Notes as is standard. 

The Docker tags are described in the README. If we had a "supported tags" section it would be entirely this:
- [`latest`](https://github.com/cloudposse/geodesic/blob/master/os/alpine/Dockerfile.alpine), [`latest-alpine`](https://github.com/cloudposse/geodesic/blob/master/os/alpine/Dockerfile.alpine)
- [`latest-debian`](https://github.com/cloudposse/geodesic/blob/master/os/debian/Dockerfile.debian)

The first problem with that is that we discourage people from actually using `latest` tags because we want them to stay in control of their updates. I think the bigger problem is that such a section is likely to be somewhat misleading, because a lot of Geodesic is configured outside the Dockerfile.  Geodesic is mostly a collection of tools, and most of the tools are updated to whatever is current when the release is built. Many of the rest of the explicitly versioned tools are versioned in external files like `requirements.txt`. So seeing that the Dockerfile did or did not change is not going to be as helpful as you might think.

We do not have separate release channels for Geodesic (e.g. stable, edge, nightly), we just have regular releases, roughly once a week, although sometimes more often if we have a bugfix to release or a feature to add. It is rare that a release has significant breakage, but when one does, we retroactively mark it as a "pre-release" so people are warned, and of course we fix it promptly. We and our clients use Geodesic literally every day, so significant problems are unlikely to linger. 

Would it have been better if the Docker Hub documentation just said "See GitHub README" or something like that, with a link to the GitHub repo? (Assuming we fix #689 :smile:)

**Comment by Nuru** [comment]
@jonassteinberg1 I am closing this as stale and lacking information. I will reopen it if you further explain what it is you would like us to do and it fits our recommended usage and release patterns.
