### ISSUE TITLE
Add a `destroy` command to the wrapper script to support removing the currently running geodesic container

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/geodesic#798]
## Describe the Feature

It would be great to have a `geodesic destroy` or similar command to remove the currently running image. 

## Use Case

This would help in clearing the existing container in the case that the user no longer wants it around.

## Describe Ideal Solution

`geodesic destroy` would lookup the running geodesic container ID and issue a `docker rm $CONTAINER_ID` against it. 

## Alternatives Considered

N/A

## Additional Context

N/A

**Comment by Nuru** [comment]
I am inclined to close/refuse this request, because it seems to me to be a scary option, because it terminates all running shells without doing cleanup like saving shell history. 

You can specify a container by name in the Docker CLI, e.g.

```
docker rm -f geodesic
```

which both seems to be easy enough to not warrant adding a separate Geodesic command and avoids Cloud Posse advocating or supporting such behavior.

**Comment by Nuru** [comment]
@Gowiem @osterman I'm a little unclear about what you want.

We recommend using the installed wrapper, which automatically removes the container image on termination, and has commands
- `stop` to stop the running Geodesic image
- `uninstall` to delete the Geodesic container and image (although it does not delete the wrapper itself)

If not using the installed wrapper, you can remove the container automatically with the `--rm` option to `docker run`. 

If not using the installed wrapper and not using `--rm`, I am not sure how we can help you. Please elaborate.

**Comment by Nuru** [comment]
Closing as `geodesic stop` seems to do what is requested. Reopen with more detail if `geodesic stop` is not sufficient.
