### ISSUE TITLE
Demo Video Needs to be Updated

### ISSUE THREAD

**Issue by kostyrev** [cloudposse/geodesic#89]
I was hoping to watch your demo but after 2 minutes of waiting and staring at rotating backslash I gave up.  
Why don't you use asciinema for this kind of thing. It can cut long pauses or provides a slide to skip certain parts of a video.

**Comment by osterman** [comment]
Yes - the demo is due for a revamp. I do like `asciinema`, but don't like that you cannot embed an animated gif (last I checked) in addition to their standard player. A lot has improved since this screencast, so we'll work on recording a few new ones (probably via `asciinema`) to demonstrate the current functionality. I think that will make the value proposition of `geodesic` a lot less opaque and make it easier for people to get started with it.

**Comment by osterman** [comment]
Looks like there's now an official tool by `asciinema` to generate gifs: https://github.com/asciinema/asciicast2gif

**Comment by osterman** [comment]
Updated video using `asciinema` has been posted here: https://docs.cloudposse.com/geodesic/#demo

**Comment by albertsj1** [comment]
This is a pretty old open issue, but the demo video still does not work.  It doesn't say in this ticket, but I'm referring to the Demo video link in the [README Screenshots section](https://github.com/cloudposse/geodesic#screenshots).

**Comment by Nuru** [comment]
Closed via #898
